spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/inventory_management
    username: postgres
    password: bony
    driver-class-name: org.postgresql.Driver


  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

app:
  jwt-secret: mySecretKey123456789012345678901234567890123456789012345678901234567890
  jwt-expiration-milliseconds: 86400000

server:
  port: 8080

logging:
  level:
    com.tritva.Inventory_Management: DEBUG
